version: '3.8'

services:
  discord-bot:
    build: .
    container_name: ticket-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./transcripts:/app/transcripts
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
